;; -*- mode: eask; lexical-binding: t -*-

(package "flymake"
         "0.4.16"
         "a universal on-the-fly syntax checker")

(website-url "https://github.com/flymake/emacs-flymake")
(keywords "c" "languages" "tools")

(package-file "flymake.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
